name: End-to-end tests
on:
  schedule:
    - cron: '0 */12 * * *'
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
