name: End-to-end tests
on:
  schedule:
    - cron: '0 */12 * * *'
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Cypress run
        uses: cypress-io/github-action@v4
