name: End-to-end tests
on:
  schedule:
    - cron: '0 */12 * * *'
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cypress run
        uses: cypress-io/github-action@v4
